### ISSUE TITLE
x.ascan not working for snd Aerotech motors in XCS3

### ISSUE THREAD

**Issue by Yanwen-Sun** [pcdshub/hxrsnd#109]
In [5]: x.ascan(snd.t1.th1, 23.186, 23.189,10,120,record = True)
INFO     DAQ is not connected. Attempting to connect...
INFO     Connected to DAQ
INFO     Daq configured: events=120, record=True, use_l3t=False, controls=[T1 TH1
  PV:            XCS:SND:T1:TH1
  Enabled:                 True
  Faulted:                False
  State:                     Go
  Position:            23.18705
  Dial:             -143.698395
  Limits:            (-150, 59)
], begin_sleep=0
ERROR    Run aborted
Traceback (most recent call last):
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'cam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 1330, in _run
    stashed_exception or resp)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/plans.py", line 1101, in scan
    per_step=per_step, md=_md))
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/plans.py", line 995, in scan_nd
    return (yield from inner_scan_nd())
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 528, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 946, in unstage_devices
    yield Msg('unstage', d)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 1413, in _run
    new_response = await coro(msg)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 2172, in _unstage
    result = obj.unstage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 598, in unstage
    device.unstage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 596, in unstage
    device = getattr(self, attr)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 225, in __get__
    return instance._instantiate_component(self.attr)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 1218, in _instantiate_component
    self._signals[attr] = cpt.create_component(self)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 182, in create_component
    cpt_inst.wait_for_connection()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 1153, in wait_for_connection
    raise TimeoutError('; '.join(reasons))
TimeoutError: Failed to connect to all signals: snd_dcc_cam.dcc.cam.image2.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE2:PluginType_RBV), snd_dcc_cam.dcc.cam.stats2.plugin_type (XCS:SND:DIA:DCC:CAM:Stats2:PluginType_RBV), snd_dcc_cam.dcc.cam.hdf51.plugin_type (XCS:SND:DIA:DCC:CAM:HDF51:PluginType_RBV), snd_dcc_cam.dcc.cam.image1.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE1:PluginType_RBV), snd_dcc_cam.dcc.cam.image1_roi.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE1:ROI:PluginType_RBV), snd_dcc_cam.dcc.cam.image1_cc.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE1:CC:PluginType_RBV), snd_dcc_cam.dcc.cam.image1_proc.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE1:Proc:PluginType_RBV), snd_dcc_cam.dcc.cam.image1_over.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE1:Over:PluginType_RBV), snd_dcc_cam.dcc.cam.image2_roi.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE2:ROI:PluginType_RBV), snd_dcc_cam.dcc.cam.image2_cc.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE2:CC:PluginType_RBV), snd_dcc_cam.dcc.cam.image2_proc.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE2:Proc:PluginType_RBV), snd_dcc_cam.dcc.cam.image2_over.plugin_type (XCS:SND:DIA:DCC:CAM:IMAGE2:Over:PluginType_RBV), snd_dcc_cam.dcc.cam.thumbnail.plugin_type (XCS:SND:DIA:DCC:CAM:THUMBNAIL:PluginType_RBV), snd_dcc_cam.dcc.cam.thumbnail_roi.plugin_type (XCS:SND:DIA:DCC:CAM:THUMBNAIL:ROI:PluginType_RBV), snd_dcc_cam.dcc.cam.thumbnail_cc.plugin_type (XCS:SND:DIA:DCC:CAM:THUMBNAIL:CC:PluginType_RBV), snd_dcc_cam.dcc.cam.thumbnail_proc.plugin_type (XCS:SND:DIA:DCC:CAM:THUMBNAIL:Proc:PluginType_RBV), snd_dcc_cam.dcc.cam.thumbnail_over.plugin_type (XCS:SND:DIA:DCC:CAM:THUMBNAIL:Over:PluginType_RBV), snd_dcc_cam.dcc.cam.cc1.plugin_type (XCS:SND:DIA:DCC:CAM:CC1:PluginType_RBV), snd_dcc_cam.dcc.cam.cc2.plugin_type (XCS:SND:DIA:DCC:CAM:CC2:PluginType_RBV), snd_dcc_cam.dcc.cam.jpeg1.plugin_type (XCS:SND:DIA:DCC:CAM:JPEG1:PluginType_RBV), snd_dcc_cam.dcc.cam.netcdf1.plugin_type (XCS:SND:DIA:DCC:CAM:NetCDF1:PluginType_RBV), snd_dcc_cam.dcc.cam.nexus1.plugin_type (XCS:SND:DIA:DCC:CAM:Nexus1:PluginType_RBV), snd_dcc_cam.dcc.cam.over1.plugin_type (XCS:SND:DIA:DCC:CAM:Over1:PluginType_RBV), snd_dcc_cam.dcc.cam.proc1.plugin_type (XCS:SND:DIA:DCC:CAM:Proc1:PluginType_RBV), snd_dcc_cam.dcc.cam.roi1.plugin_type (XCS:SND:DIA:DCC:CAM:ROI1:PluginType_RBV), snd_dcc_cam.dcc.cam.roi2.plugin_type (XCS:SND:DIA:DCC:CAM:ROI2:PluginType_RBV), snd_dcc_cam.dcc.cam.roi3.plugin_type (XCS:SND:DIA:DCC:CAM:ROI3:PluginType_RBV), snd_dcc_cam.dcc.cam.roi4.plugin_type (XCS:SND:DIA:DCC:CAM:ROI4:PluginType_RBV), snd_dcc_cam.dcc.cam.stats1.plugin_type (XCS:SND:DIA:DCC:CAM:Stats1:PluginType_RBV), snd_dcc_cam.dcc.cam.stats3.plugin_type (XCS:SND:DIA:DCC:CAM:Stats3:PluginType_RBV), snd_dcc_cam.dcc.cam.stats4.plugin_type (XCS:SND:DIA:DCC:CAM:Stats4:PluginType_RBV), snd_dcc_cam.dcc.cam.stats5.plugin_type (XCS:SND:DIA:DCC:CAM:Stats5:PluginType_RBV), snd_dcc_cam.dcc.cam.tiff1.plugin_type (XCS:SND:DIA:DCC:CAM:TIFF1:PluginType_RBV), snd_dcc_cam.dcc.cam.trans1.plugin_type (XCS:SND:DIA:DCC:CAM:Trans1:PluginType_RBV)
INFO     Move completed for 'T1 TH1'.

**Comment by Yanwen-Sun** [comment]
I tried umvr which works, mvr still has issues... not sure this is related with the scan failure... in principle ascan shouldn't have dependencies with relative motions.

**Comment by klauer** [comment]
@Yanwen-Sun can you confirm that the camera IOC is running? According to that message, it's complaining about this device: "XCS:SND:DIA:DCC:CAM"

**Comment by Yanwen-Sun** [comment]
We don't have that camera connected.

**Comment by Yanwen-Sun** [comment]
Why will the scan need to connect to the camera?

**Comment by dlzhu** [comment]
No idea why the camera has anything to do with the scan. The camera was actually never physically installed although the IOC was setup early on called likely gige_snd_dcc.

**Comment by klauer** [comment]
The overall idea is that your entire device (in this case, `snd`) must be connected before the scan will be allowed to take place. It doesn't know that the camera isn't essential for your operations.

If it's truly unneeded, we can remove it from the device. I'm not familiar enough with your hutch to make that call myself, though.

**Comment by Yanwen-Sun** [comment]
**More errors**
In [5]: x.ascan(snd.t1.th1, 23.186, 23.189,10,120,record = True)
INFO     DAQ is not connected. Attempting to connect...
INFO     Connected to DAQ
INFO     Daq configured: events=120, record=True, use_l3t=False, controls=[T1 TH1
  PV:            XCS:SND:T1:TH1
  Enabled:                 True
  Faulted:                False
  State:                     Go
  Position:           23.186045
  Dial:             -143.697389
  Limits:            (-150, 59)
], begin_sleep=0
ERROR    Run aborted
Traceback (most recent call last):
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 1353, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/plans.py", line 1101, in scan
    per_step=per_step, md=_md))
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/plans.py", line 995, in scan_nd
    return (yield from inner_scan_nd())
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 949, in inner
    yield from stage_devices()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/preprocessors.py", line 942, in stage_devices
    yield Msg('stage', d)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 1413, in _run
    new_response = await coro(msg)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/bluesky/run_engine.py", line 2156, in _stage
    result = obj.stage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 559, in stage
    device.stage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 559, in stage
    device.stage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/areadetector/base.py", line 289, in stage
    ret = super().stage(*args, **kwargs)
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/device.py", line 559, in stage
    device.stage()
  File "/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/areadetector/plugins.py", line 919, in stage
    raise UnprimedPlugin(f"The plugin {self.dotted_name} on the "
ophyd.utils.errors.UnprimedPlugin: The plugin delay.calib_detector.hdf51 on the area detector with name snd has not been primed.
INFO     Moving snd_t1_th1 from 23.186042779203504 to 23.186044635002176
INFO     snd_t1_th1 reached position 23.186042779203504
INFO     Move completed for 'T1 TH1'.

**Comment by ZLLentz** [comment]
In general, `hxrsnd` was written in a monolithic way that will cause these sorts of issues repeatedly.

The scan required the camera because the class we wanted to scan included the camera in it, even though we didn't care about the camera. I think creating one massive `ophyd` object is a huge mistake every time and I think we need to refactor `hxrsnd` to not implement it like this.

**Comment by Yanwen-Sun** [comment]
It works now thanks. I am going to start a new ticket on the snd.delay mv
